### ISSUE TITLE
Android: investigate Unity@2018 requesting phone permissions

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#842]
* Unity version: 2018
* Mapbox SDK version: 1.4.3
* The platform you're building to: Android
* A description of what you're trying to do:
With 2018 Unity started requesting `Phone Permission` on Android (which 2017 didn't) and which we don't need in our SDK:
![image](https://user-images.githubusercontent.com/4549888/41047049-f82d29f2-69ab-11e8-8f5c-ea548cfb03ab.png)

**TODO:**
- [ ] investigate what triggers that permission request
- [ ] disable, if possible
  - [ ] otherwise document that the request is not by our SDK

----

I tried disabling `Analytics` as this was my first hunch but that didn't change required permissions.

![image](https://user-images.githubusercontent.com/4549888/41047189-47a14f5e-69ac-11e8-860c-07a0ec151f1c.png)

**Comment by ataylor09** [comment]
Is there an update to the status of this issue? I just encountered this in my app using Mapbox for Unity
